<?php
$j=1;
if(isset($_POST['submit'])){
	//echo "<br>Proses Benar</br>";
	include 'koneksi.php';
	session_start();
	$date = date('Y-m-d');
	$nama=$_SESSION['nama'];
	$vmde=$_POST['VMDE'];
	$vmndea=$_POST['VMNDEA'];
	$vmnder=$_POST['VMNDER'];
	$tempm=$_POST['TempM'];
	$arusr=$_POST['ArusR'];
	$aruss=$_POST['ArusS'];
	$arust=$_POST['ArusT'];
	$ket=$_POST['Ket'];
	
	$insert = mysql_query("UPDATE form_checklist_line_6_tdo SET 	
						Line_Drive_OL_VMDE = '$vmde[$j]',
				Line_Drive_OL_VMNDEA = '$vmndea[$j]',
				Line_Drive_OL_VMNDER = '$vmnder[$j]',
				Line_Drive_OL_TempM = '$tempm[$j]',
				Line_Drive_OL_ArusR = '$arusr[$j]',
				Line_Drive_OL_ArusS = '$aruss[$j]',
				Line_Drive_OL_ArusT = '$arust[$j]',
				Line_Drive_OL_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET

				Cooling_Drive_OL_VMDE = '$vmde[$j]',
				Cooling_Drive_OL_VMNDEA = '$vmndea[$j]',
				Cooling_Drive_OL_VMNDER = '$vmnder[$j]',
				Cooling_Drive_OL_TempM = '$tempm[$j]',
				Cooling_Drive_OL_ArusR = '$arusr[$j]',
				Cooling_Drive_OL_ArusS = '$aruss[$j]',
				Cooling_Drive_OL_ArusT = '$arust[$j]',
				Cooling_Drive_OL_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Line_Drive_OR_VMDE = '$vmde[$j]',
				Line_Drive_OR_VMNDEA = '$vmndea[$j]',
				Line_Drive_OR_VMNDER = '$vmnder[$j]',
				Line_Drive_OR_TempM = '$tempm[$j]',
				Line_Drive_OR_ArusR = '$arusr[$j]',
				Line_Drive_OR_ArusS = '$aruss[$j]',
				Line_Drive_OR_ArusT = '$arust[$j]',
				Line_Drive_OR_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Cooling_Drive_OR_VMDE = '$vmde[$j]',
				Cooling_Drive_OR_VMNDEA = '$vmndea[$j]',
				Cooling_Drive_OR_VMNDER = '$vmnder[$j]',
				Cooling_Drive_OR_TempM = '$tempm[$j]',
				Cooling_Drive_OR_ArusR = '$arusr[$j]',
				Cooling_Drive_OR_ArusS = '$aruss[$j]',
				Cooling_Drive_OR_ArusT = '$arust[$j]',
				Cooling_Drive_OR_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat1_Fan1_VMDE = '$vmde[$j]',
				Preheat1_Fan1_VMNDEA = '$vmndea[$j]',
				Preheat1_Fan1_VMNDER = '$vmnder[$j]',
				Preheat1_Fan1_TempM = '$tempm[$j]',
				Preheat1_Fan1_ArusR = '$arusr[$j]',
				Preheat1_Fan1_ArusS = '$aruss[$j]',
				Preheat1_Fan1_ArusT = '$arust[$j]',
				Preheat1_Fan1_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat1_Fan2_VMDE = '$vmde[$j]',
				Preheat1_Fan2_VMNDEA = '$vmndea[$j]',
				Preheat1_Fan2_VMNDER = '$vmnder[$j]',
				Preheat1_Fan2_TempM = '$tempm[$j]',
				Preheat1_Fan2_ArusR = '$arusr[$j]',
				Preheat1_Fan2_ArusS = '$aruss[$j]',
				Preheat1_Fan2_ArusT = '$arust[$j]',
				Preheat1_Fan2_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat1_Fan3_VMDE = '$vmde[$j]',
				Preheat1_Fan3_VMNDEA = '$vmndea[$j]',
				Preheat1_Fan3_VMNDER = '$vmnder[$j]',
				Preheat1_Fan3_TempM = '$tempm[$j]',
				Preheat1_Fan3_ArusR = '$arusr[$j]',
				Preheat1_Fan3_ArusS = '$aruss[$j]',
				Preheat1_Fan3_ArusT = '$arust[$j]',
				Preheat1_Fan3_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat2_Fan1_VMDE = '$vmde[$j]',
				Preheat2_Fan1_VMNDEA = '$vmndea[$j]',
				Preheat2_Fan1_VMNDER = '$vmnder[$j]',
				Preheat2_Fan1_TempM = '$tempm[$j]',
				Preheat2_Fan1_ArusR = '$arusr[$j]',
				Preheat2_Fan1_ArusS = '$aruss[$j]',
				Preheat2_Fan1_ArusT = '$arust[$j]',
				Preheat2_Fan1_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat2_Fan2_VMDE = '$vmde[$j]',
				Preheat2_Fan2_VMNDEA = '$vmndea[$j]',
				Preheat2_Fan2_VMNDER = '$vmnder[$j]',
				Preheat2_Fan2_TempM = '$tempm[$j]',
				Preheat2_Fan2_ArusR = '$arusr[$j]',
				Preheat2_Fan2_ArusS = '$aruss[$j]',
				Preheat2_Fan2_ArusT = '$arust[$j]',
				Preheat2_Fan2_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat2_Fan3_VMDE = '$vmde[$j]',
				Preheat2_Fan3_VMNDEA = '$vmndea[$j]',
				Preheat2_Fan3_VMNDER = '$vmnder[$j]',
				Preheat2_Fan3_TempM = '$tempm[$j]',
				Preheat2_Fan3_ArusR = '$arusr[$j]',
				Preheat2_Fan3_ArusS = '$aruss[$j]',
				Preheat2_Fan3_ArusT = '$arust[$j]',
				Preheat2_Fan3_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat3_Fan1_VMDE = '$vmde[$j]',
				Preheat3_Fan1_VMNDEA = '$vmndea[$j]',
				Preheat3_Fan1_VMNDER = '$vmnder[$j]',
				Preheat3_Fan1_TempM = '$tempm[$j]',
				Preheat3_Fan1_ArusR = '$arusr[$j]',
				Preheat3_Fan1_ArusS = '$aruss[$j]',
				Preheat3_Fan1_ArusT = '$arust[$j]',
				Preheat3_Fan1_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat3_Fan2_VMDE = '$vmde[$j]',
				Preheat3_Fan2_VMNDEA = '$vmndea[$j]',
				Preheat3_Fan2_VMNDER = '$vmnder[$j]',
				Preheat3_Fan2_TempM = '$tempm[$j]',
				Preheat3_Fan2_ArusR = '$arusr[$j]',
				Preheat3_Fan2_ArusS = '$aruss[$j]',
				Preheat3_Fan2_ArusT = '$arust[$j]',
				Preheat3_Fan2_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat3_Fan3_VMDE = '$vmde[$j]',
				Preheat3_Fan3_VMNDEA = '$vmndea[$j]',
				Preheat3_Fan3_VMNDER = '$vmnder[$j]',
				Preheat3_Fan3_TempM = '$tempm[$j]',
				Preheat3_Fan3_ArusR = '$arusr[$j]',
				Preheat3_Fan3_ArusS = '$aruss[$j]',
				Preheat3_Fan3_ArusT = '$arust[$j]',
				Preheat3_Fan3_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat4_Fan1_VMDE = '$vmde[$j]',
				Preheat4_Fan1_VMNDEA = '$vmndea[$j]',
				Preheat4_Fan1_VMNDER = '$vmnder[$j]',
				Preheat4_Fan1_TempM = '$tempm[$j]',
				Preheat4_Fan1_ArusR = '$arusr[$j]',
				Preheat4_Fan1_ArusS = '$aruss[$j]',
				Preheat4_Fan1_ArusT = '$arust[$j]',
				Preheat4_Fan1_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat4_Fan2_VMDE = '$vmde[$j]',
				Preheat4_Fan2_VMNDEA = '$vmndea[$j]',
				Preheat4_Fan2_VMNDER = '$vmnder[$j]',
				Preheat4_Fan2_TempM = '$tempm[$j]',
				Preheat4_Fan2_ArusR = '$arusr[$j]',
				Preheat4_Fan2_ArusS = '$aruss[$j]',
				Preheat4_Fan2_ArusT = '$arust[$j]',
				Preheat4_Fan2_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat4_Fan3_VMDE = '$vmde[$j]',
				Preheat4_Fan3_VMNDEA = '$vmndea[$j]',
				Preheat4_Fan3_VMNDER = '$vmnder[$j]',
				Preheat4_Fan3_TempM = '$tempm[$j]',
				Preheat4_Fan3_ArusR = '$arusr[$j]',
				Preheat4_Fan3_ArusS = '$aruss[$j]',
				Preheat4_Fan3_ArusT = '$arust[$j]',
				Preheat4_Fan3_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat5_Fan1_VMDE = '$vmde[$j]',
				Preheat5_Fan1_VMNDEA = '$vmndea[$j]',
				Preheat5_Fan1_VMNDER = '$vmnder[$j]',
				Preheat5_Fan1_TempM = '$tempm[$j]',
				Preheat5_Fan1_ArusR = '$arusr[$j]',
				Preheat5_Fan1_ArusS = '$aruss[$j]',
				Preheat5_Fan1_ArusT = '$arust[$j]',
				Preheat5_Fan1_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat5_Fan2_VMDE = '$vmde[$j]',
				Preheat5_Fan2_VMNDEA = '$vmndea[$j]',
				Preheat5_Fan2_VMNDER = '$vmnder[$j]',
				Preheat5_Fan2_TempM = '$tempm[$j]',
				Preheat5_Fan2_ArusR = '$arusr[$j]',
				Preheat5_Fan2_ArusS = '$aruss[$j]',
				Preheat5_Fan2_ArusT = '$arust[$j]',
				Preheat5_Fan2_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat5_Fan3_VMDE = '$vmde[$j]',
				Preheat5_Fan3_VMNDEA = '$vmndea[$j]',
				Preheat5_Fan3_VMNDER = '$vmnder[$j]',
				Preheat5_Fan3_TempM = '$tempm[$j]',
				Preheat5_Fan3_ArusR = '$arusr[$j]',
				Preheat5_Fan3_ArusS = '$aruss[$j]',
				Preheat5_Fan3_ArusT = '$arust[$j]',
				Preheat5_Fan3_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat6_Fan1_VMDE = '$vmde[$j]',
				Preheat6_Fan1_VMNDEA = '$vmndea[$j]',
				Preheat6_Fan1_VMNDER = '$vmnder[$j]',
				Preheat6_Fan1_TempM = '$tempm[$j]',
				Preheat6_Fan1_ArusR = '$arusr[$j]',
				Preheat6_Fan1_ArusS = '$aruss[$j]',
				Preheat6_Fan1_ArusT = '$arust[$j]',
				Preheat6_Fan1_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat6_Fan2_VMDE = '$vmde[$j]',
				Preheat6_Fan2_VMNDEA = '$vmndea[$j]',
				Preheat6_Fan2_VMNDER = '$vmnder[$j]',
				Preheat6_Fan2_TempM = '$tempm[$j]',
				Preheat6_Fan2_ArusR = '$arusr[$j]',
				Preheat6_Fan2_ArusS = '$aruss[$j]',
				Preheat6_Fan2_ArusT = '$arust[$j]',
				Preheat6_Fan2_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Preheat6_Fan3_VMDE = '$vmde[$j]',
				Preheat6_Fan3_VMNDEA = '$vmndea[$j]',
				Preheat6_Fan3_VMNDER = '$vmnder[$j]',
				Preheat6_Fan3_TempM = '$tempm[$j]',
				Preheat6_Fan3_ArusR = '$arusr[$j]',
				Preheat6_Fan3_ArusS = '$aruss[$j]',
				Preheat6_Fan3_ArusT = '$arust[$j]',
				Preheat6_Fan3_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing1_Fan1_Top_VMDE = '$vmde[$j]',
				Drawing1_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Drawing1_Fan1_Top_VMNDER = '$vmnder[$j]',
				Drawing1_Fan1_Top_TempM = '$tempm[$j]',
				Drawing1_Fan1_Top_ArusR = '$arusr[$j]',
				Drawing1_Fan1_Top_ArusS = '$aruss[$j]',
				Drawing1_Fan1_Top_ArusT = '$arust[$j]',
				Drawing1_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing1_Fan2_Top_VMDE = '$vmde[$j]',
				Drawing1_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Drawing1_Fan2_Top_VMNDER = '$vmnder[$j]',
				Drawing1_Fan2_Top_TempM = '$tempm[$j]',
				Drawing1_Fan2_Top_ArusR = '$arusr[$j]',
				Drawing1_Fan2_Top_ArusS = '$aruss[$j]',
				Drawing1_Fan2_Top_ArusT = '$arust[$j]',
				Drawing1_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing1_Fan1_Bot_VMDE = '$vmde[$j]',
				Drawing1_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Drawing1_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Drawing1_Fan1_Bot_TempM = '$tempm[$j]',
				Drawing1_Fan1_Bot_ArusR = '$arusr[$j]',
				Drawing1_Fan1_Bot_ArusS = '$aruss[$j]',
				Drawing1_Fan1_Bot_ArusT = '$arust[$j]',
				Drawing1_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing1_Fan2_Bot_VMDE = '$vmde[$j]',
				Drawing1_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Drawing1_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Drawing1_Fan2_Bot_TempM = '$tempm[$j]',
				Drawing1_Fan2_Bot_ArusR = '$arusr[$j]',
				Drawing1_Fan2_Bot_ArusS = '$aruss[$j]',
				Drawing1_Fan2_Bot_ArusT = '$arust[$j]',
				Drawing1_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing2_Fan1_Top_VMDE = '$vmde[$j]',
				Drawing2_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Drawing2_Fan1_Top_VMNDER = '$vmnder[$j]',
				Drawing2_Fan1_Top_TempM = '$tempm[$j]',
				Drawing2_Fan1_Top_ArusR = '$arusr[$j]',
				Drawing2_Fan1_Top_ArusS = '$aruss[$j]',
				Drawing2_Fan1_Top_ArusT = '$arust[$j]',
				Drawing2_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing2_Fan2_Top_VMDE = '$vmde[$j]',
				Drawing2_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Drawing2_Fan2_Top_VMNDER = '$vmnder[$j]',
				Drawing2_Fan2_Top_TempM = '$tempm[$j]',
				Drawing2_Fan2_Top_ArusR = '$arusr[$j]',
				Drawing2_Fan2_Top_ArusS = '$aruss[$j]',
				Drawing2_Fan2_Top_ArusT = '$arust[$j]',
				Drawing2_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing2_Fan1_Bot_VMDE = '$vmde[$j]',
				Drawing2_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Drawing2_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Drawing2_Fan1_Bot_TempM = '$tempm[$j]',
				Drawing2_Fan1_Bot_ArusR = '$arusr[$j]',
				Drawing2_Fan1_Bot_ArusS = '$aruss[$j]',
				Drawing2_Fan1_Bot_ArusT = '$arust[$j]',
				Drawing2_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing2_Fan2_Bot_VMDE = '$vmde[$j]',
				Drawing2_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Drawing2_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Drawing2_Fan2_Bot_TempM = '$tempm[$j]',
				Drawing2_Fan2_Bot_ArusR = '$arusr[$j]',
				Drawing2_Fan2_Bot_ArusS = '$aruss[$j]',
				Drawing2_Fan2_Bot_ArusT = '$arust[$j]',
				Drawing2_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing3_Fan1_Top_VMDE = '$vmde[$j]',
				Drawing3_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Drawing3_Fan1_Top_VMNDER = '$vmnder[$j]',
				Drawing3_Fan1_Top_TempM = '$tempm[$j]',
				Drawing3_Fan1_Top_ArusR = '$arusr[$j]',
				Drawing3_Fan1_Top_ArusS = '$aruss[$j]',
				Drawing3_Fan1_Top_ArusT = '$arust[$j]',
				Drawing3_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing3_Fan2_Top_VMDE = '$vmde[$j]',
				Drawing3_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Drawing3_Fan2_Top_VMNDER = '$vmnder[$j]',
				Drawing3_Fan2_Top_TempM = '$tempm[$j]',
				Drawing3_Fan2_Top_ArusR = '$arusr[$j]',
				Drawing3_Fan2_Top_ArusS = '$aruss[$j]',
				Drawing3_Fan2_Top_ArusT = '$arust[$j]',
				Drawing3_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing3_Fan1_Bot_VMDE = '$vmde[$j]',
				Drawing3_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Drawing3_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Drawing3_Fan1_Bot_TempM = '$tempm[$j]',
				Drawing3_Fan1_Bot_ArusR = '$arusr[$j]',
				Drawing3_Fan1_Bot_ArusS = '$aruss[$j]',
				Drawing3_Fan1_Bot_ArusT = '$arust[$j]',
				Drawing3_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing3_Fan2_Bot_VMDE = '$vmde[$j]',
				Drawing3_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Drawing3_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Drawing3_Fan2_Bot_TempM = '$tempm[$j]',
				Drawing3_Fan2_Bot_ArusR = '$arusr[$j]',
				Drawing3_Fan2_Bot_ArusS = '$aruss[$j]',
				Drawing3_Fan2_Bot_ArusT = '$arust[$j]',
				Drawing3_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing4_Fan1_Top_VMDE = '$vmde[$j]',
				Drawing4_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Drawing4_Fan1_Top_VMNDER = '$vmnder[$j]',
				Drawing4_Fan1_Top_TempM = '$tempm[$j]',
				Drawing4_Fan1_Top_ArusR = '$arusr[$j]',
				Drawing4_Fan1_Top_ArusS = '$aruss[$j]',
				Drawing4_Fan1_Top_ArusT = '$arust[$j]',
				Drawing4_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing4_Fan2_Top_VMDE = '$vmde[$j]',
				Drawing4_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Drawing4_Fan2_Top_VMNDER = '$vmnder[$j]',
				Drawing4_Fan2_Top_TempM = '$tempm[$j]',
				Drawing4_Fan2_Top_ArusR = '$arusr[$j]',
				Drawing4_Fan2_Top_ArusS = '$aruss[$j]',
				Drawing4_Fan2_Top_ArusT = '$arust[$j]',
				Drawing4_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing4_Fan1_Bot_VMDE = '$vmde[$j]',
				Drawing4_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Drawing4_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Drawing4_Fan1_Bot_TempM = '$tempm[$j]',
				Drawing4_Fan1_Bot_ArusR = '$arusr[$j]',
				Drawing4_Fan1_Bot_ArusS = '$aruss[$j]',
				Drawing4_Fan1_Bot_ArusT = '$arust[$j]',
				Drawing4_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing4_Fan2_Bot_VMDE = '$vmde[$j]',
				Drawing4_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Drawing4_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Drawing4_Fan2_Bot_TempM = '$tempm[$j]',
				Drawing4_Fan2_Bot_ArusR = '$arusr[$j]',
				Drawing4_Fan2_Bot_ArusS = '$aruss[$j]',
				Drawing4_Fan2_Bot_ArusT = '$arust[$j]',
				Drawing4_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing5_Fan1_Top_VMDE = '$vmde[$j]',
				Drawing5_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Drawing5_Fan1_Top_VMNDER = '$vmnder[$j]',
				Drawing5_Fan1_Top_TempM = '$tempm[$j]',
				Drawing5_Fan1_Top_ArusR = '$arusr[$j]',
				Drawing5_Fan1_Top_ArusS = '$aruss[$j]',
				Drawing5_Fan1_Top_ArusT = '$arust[$j]',
				Drawing5_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing5_Fan2_Top_VMDE = '$vmde[$j]',
				Drawing5_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Drawing5_Fan2_Top_VMNDER = '$vmnder[$j]',
				Drawing5_Fan2_Top_TempM = '$tempm[$j]',
				Drawing5_Fan2_Top_ArusR = '$arusr[$j]',
				Drawing5_Fan2_Top_ArusS = '$aruss[$j]',
				Drawing5_Fan2_Top_ArusT = '$arust[$j]',
				Drawing5_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing5_Fan1_Bot_VMDE = '$vmde[$j]',
				Drawing5_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Drawing5_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Drawing5_Fan1_Bot_TempM = '$tempm[$j]',
				Drawing5_Fan1_Bot_ArusR = '$arusr[$j]',
				Drawing5_Fan1_Bot_ArusS = '$aruss[$j]',
				Drawing5_Fan1_Bot_ArusT = '$arust[$j]',
				Drawing5_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Drawing5_Fan2_Bot_VMDE = '$vmde[$j]',
				Drawing5_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Drawing5_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Drawing5_Fan2_Bot_TempM = '$tempm[$j]',
				Drawing5_Fan2_Bot_ArusR = '$arusr[$j]',
				Drawing5_Fan2_Bot_ArusS = '$aruss[$j]',
				Drawing5_Fan2_Bot_ArusT = '$arust[$j]',
				Drawing5_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing1_Fan1_Top_VMDE = '$vmde[$j]',
				Annealing1_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Annealing1_Fan1_Top_VMNDER = '$vmnder[$j]',
				Annealing1_Fan1_Top_TempM = '$tempm[$j]',
				Annealing1_Fan1_Top_ArusR = '$arusr[$j]',
				Annealing1_Fan1_Top_ArusS = '$aruss[$j]',
				Annealing1_Fan1_Top_ArusT = '$arust[$j]',
				Annealing1_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing1_Fan2_Top_VMDE = '$vmde[$j]',
				Annealing1_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Annealing1_Fan2_Top_VMNDER = '$vmnder[$j]',
				Annealing1_Fan2_Top_TempM = '$tempm[$j]',
				Annealing1_Fan2_Top_ArusR = '$arusr[$j]',
				Annealing1_Fan2_Top_ArusS = '$aruss[$j]',
				Annealing1_Fan2_Top_ArusT = '$arust[$j]',
				Annealing1_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing1_Fan1_Bot_VMDE = '$vmde[$j]',
				Annealing1_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Annealing1_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Annealing1_Fan1_Bot_TempM = '$tempm[$j]',
				Annealing1_Fan1_Bot_ArusR = '$arusr[$j]',
				Annealing1_Fan1_Bot_ArusS = '$aruss[$j]',
				Annealing1_Fan1_Bot_ArusT = '$arust[$j]',
				Annealing1_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing1_Fan2_Bot_VMDE = '$vmde[$j]',
				Annealing1_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Annealing1_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Annealing1_Fan2_Bot_TempM = '$tempm[$j]',
				Annealing1_Fan2_Bot_ArusR = '$arusr[$j]',
				Annealing1_Fan2_Bot_ArusS = '$aruss[$j]',
				Annealing1_Fan2_Bot_ArusT = '$arust[$j]',
				Annealing1_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing2_Fan1_Top_VMDE = '$vmde[$j]',
				Annealing2_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Annealing2_Fan1_Top_VMNDER = '$vmnder[$j]',
				Annealing2_Fan1_Top_TempM = '$tempm[$j]',
				Annealing2_Fan1_Top_ArusR = '$arusr[$j]',
				Annealing2_Fan1_Top_ArusS = '$aruss[$j]',
				Annealing2_Fan1_Top_ArusT = '$arust[$j]',
				Annealing2_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing2_Fan2_Top_VMDE = '$vmde[$j]',
				Annealing2_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Annealing2_Fan2_Top_VMNDER = '$vmnder[$j]',
				Annealing2_Fan2_Top_TempM = '$tempm[$j]',
				Annealing2_Fan2_Top_ArusR = '$arusr[$j]',
				Annealing2_Fan2_Top_ArusS = '$aruss[$j]',
				Annealing2_Fan2_Top_ArusT = '$arust[$j]',
				Annealing2_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing2_Fan1_Bot_VMDE = '$vmde[$j]',
				Annealing2_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Annealing2_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Annealing2_Fan1_Bot_TempM = '$tempm[$j]',
				Annealing2_Fan1_Bot_ArusR = '$arusr[$j]',
				Annealing2_Fan1_Bot_ArusS = '$aruss[$j]',
				Annealing2_Fan1_Bot_ArusT = '$arust[$j]',
				Annealing2_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing2_Fan2_Bot_VMDE = '$vmde[$j]',
				Annealing2_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Annealing2_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Annealing2_Fan2_Bot_TempM = '$tempm[$j]',
				Annealing2_Fan2_Bot_ArusR = '$arusr[$j]',
				Annealing2_Fan2_Bot_ArusS = '$aruss[$j]',
				Annealing2_Fan2_Bot_ArusT = '$arust[$j]',
				Annealing2_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing3_Fan1_Top_VMDE = '$vmde[$j]',
				Annealing3_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Annealing3_Fan1_Top_VMNDER = '$vmnder[$j]',
				Annealing3_Fan1_Top_TempM = '$tempm[$j]',
				Annealing3_Fan1_Top_ArusR = '$arusr[$j]',
				Annealing3_Fan1_Top_ArusS = '$aruss[$j]',
				Annealing3_Fan1_Top_ArusT = '$arust[$j]',
				Annealing3_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing3_Fan2_Top_VMDE = '$vmde[$j]',
				Annealing3_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Annealing3_Fan2_Top_VMNDER = '$vmnder[$j]',
				Annealing3_Fan2_Top_TempM = '$tempm[$j]',
				Annealing3_Fan2_Top_ArusR = '$arusr[$j]',
				Annealing3_Fan2_Top_ArusS = '$aruss[$j]',
				Annealing3_Fan2_Top_ArusT = '$arust[$j]',
				Annealing3_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing3_Fan1_Bot_VMDE = '$vmde[$j]',
				Annealing3_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Annealing3_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Annealing3_Fan1_Bot_TempM = '$tempm[$j]',
				Annealing3_Fan1_Bot_ArusR = '$arusr[$j]',
				Annealing3_Fan1_Bot_ArusS = '$aruss[$j]',
				Annealing3_Fan1_Bot_ArusT = '$arust[$j]',
				Annealing3_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing3_Fan2_Bot_VMDE = '$vmde[$j]',
				Annealing3_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Annealing3_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Annealing3_Fan2_Bot_TempM = '$tempm[$j]',
				Annealing3_Fan2_Bot_ArusR = '$arusr[$j]',
				Annealing3_Fan2_Bot_ArusS = '$aruss[$j]',
				Annealing3_Fan2_Bot_ArusT = '$arust[$j]',
				Annealing3_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing4_Fan1_Top_VMDE = '$vmde[$j]',
				Annealing4_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Annealing4_Fan1_Top_VMNDER = '$vmnder[$j]',
				Annealing4_Fan1_Top_TempM = '$tempm[$j]',
				Annealing4_Fan1_Top_ArusR = '$arusr[$j]',
				Annealing4_Fan1_Top_ArusS = '$aruss[$j]',
				Annealing4_Fan1_Top_ArusT = '$arust[$j]',
				Annealing4_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing4_Fan2_Top_VMDE = '$vmde[$j]',
				Annealing4_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Annealing4_Fan2_Top_VMNDER = '$vmnder[$j]',
				Annealing4_Fan2_Top_TempM = '$tempm[$j]',
				Annealing4_Fan2_Top_ArusR = '$arusr[$j]',
				Annealing4_Fan2_Top_ArusS = '$aruss[$j]',
				Annealing4_Fan2_Top_ArusT = '$arust[$j]',
				Annealing4_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing4_Fan1_Bot_VMDE = '$vmde[$j]',
				Annealing4_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Annealing4_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Annealing4_Fan1_Bot_TempM = '$tempm[$j]',
				Annealing4_Fan1_Bot_ArusR = '$arusr[$j]',
				Annealing4_Fan1_Bot_ArusS = '$aruss[$j]',
				Annealing4_Fan1_Bot_ArusT = '$arust[$j]',
				Annealing4_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing4_Fan2_Bot_VMDE = '$vmde[$j]',
				Annealing4_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Annealing4_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Annealing4_Fan2_Bot_TempM = '$tempm[$j]',
				Annealing4_Fan2_Bot_ArusR = '$arusr[$j]',
				Annealing4_Fan2_Bot_ArusS = '$aruss[$j]',
				Annealing4_Fan2_Bot_ArusT = '$arust[$j]',
				Annealing4_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing5_Fan1_Top_VMDE = '$vmde[$j]',
				Annealing5_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Annealing5_Fan1_Top_VMNDER = '$vmnder[$j]',
				Annealing5_Fan1_Top_TempM = '$tempm[$j]',
				Annealing5_Fan1_Top_ArusR = '$arusr[$j]',
				Annealing5_Fan1_Top_ArusS = '$aruss[$j]',
				Annealing5_Fan1_Top_ArusT = '$arust[$j]',
				Annealing5_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing5_Fan2_Top_VMDE = '$vmde[$j]',
				Annealing5_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Annealing5_Fan2_Top_VMNDER = '$vmnder[$j]',
				Annealing5_Fan2_Top_TempM = '$tempm[$j]',
				Annealing5_Fan2_Top_ArusR = '$arusr[$j]',
				Annealing5_Fan2_Top_ArusS = '$aruss[$j]',
				Annealing5_Fan2_Top_ArusT = '$arust[$j]',
				Annealing5_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing5_Fan1_Bot_VMDE = '$vmde[$j]',
				Annealing5_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Annealing5_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Annealing5_Fan1_Bot_TempM = '$tempm[$j]',
				Annealing5_Fan1_Bot_ArusR = '$arusr[$j]',
				Annealing5_Fan1_Bot_ArusS = '$aruss[$j]',
				Annealing5_Fan1_Bot_ArusT = '$arust[$j]',
				Annealing5_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing5_Fan2_Bot_VMDE = '$vmde[$j]',
				Annealing5_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Annealing5_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Annealing5_Fan2_Bot_TempM = '$tempm[$j]',
				Annealing5_Fan2_Bot_ArusR = '$arusr[$j]',
				Annealing5_Fan2_Bot_ArusS = '$aruss[$j]',
				Annealing5_Fan2_Bot_ArusT = '$arust[$j]',
				Annealing5_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing6_Fan1_Top_VMDE = '$vmde[$j]',
				Annealing6_Fan1_Top_VMNDEA = '$vmndea[$j]',
				Annealing6_Fan1_Top_VMNDER = '$vmnder[$j]',
				Annealing6_Fan1_Top_TempM = '$tempm[$j]',
				Annealing6_Fan1_Top_ArusR = '$arusr[$j]',
				Annealing6_Fan1_Top_ArusS = '$aruss[$j]',
				Annealing6_Fan1_Top_ArusT = '$arust[$j]',
				Annealing6_Fan1_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing6_Fan2_Top_VMDE = '$vmde[$j]',
				Annealing6_Fan2_Top_VMNDEA = '$vmndea[$j]',
				Annealing6_Fan2_Top_VMNDER = '$vmnder[$j]',
				Annealing6_Fan2_Top_TempM = '$tempm[$j]',
				Annealing6_Fan2_Top_ArusR = '$arusr[$j]',
				Annealing6_Fan2_Top_ArusS = '$aruss[$j]',
				Annealing6_Fan2_Top_ArusT = '$arust[$j]',
				Annealing6_Fan2_Top_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing6_Fan1_Bot_VMDE = '$vmde[$j]',
				Annealing6_Fan1_Bot_VMNDEA = '$vmndea[$j]',
				Annealing6_Fan1_Bot_VMNDER = '$vmnder[$j]',
				Annealing6_Fan1_Bot_TempM = '$tempm[$j]',
				Annealing6_Fan1_Bot_ArusR = '$arusr[$j]',
				Annealing6_Fan1_Bot_ArusS = '$aruss[$j]',
				Annealing6_Fan1_Bot_ArusT = '$arust[$j]',
				Annealing6_Fan1_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Annealing6_Fan2_Bot_VMDE = '$vmde[$j]',
				Annealing6_Fan2_Bot_VMNDEA = '$vmndea[$j]',
				Annealing6_Fan2_Bot_VMNDER = '$vmnder[$j]',
				Annealing6_Fan2_Bot_TempM = '$tempm[$j]',
				Annealing6_Fan2_Bot_ArusR = '$arusr[$j]',
				Annealing6_Fan2_Bot_ArusS = '$aruss[$j]',
				Annealing6_Fan2_Bot_ArusT = '$arust[$j]',
				Annealing6_Fan2_Bot_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Film_Edge_Cool_Fan_L_VMDE = '$vmde[$j]',
				Film_Edge_Cool_Fan_L_VMNDEA = '$vmndea[$j]',
				Film_Edge_Cool_Fan_L_VMNDER = '$vmnder[$j]',
				Film_Edge_Cool_Fan_L_TempM = '$tempm[$j]',
				Film_Edge_Cool_Fan_L_ArusR = '$arusr[$j]',
				Film_Edge_Cool_Fan_L_ArusS = '$aruss[$j]',
				Film_Edge_Cool_Fan_L_ArusT = '$arust[$j]',
				Film_Edge_Cool_Fan_L_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Film_Edge_Cool_Fan_R_VMDE = '$vmde[$j]',
				Film_Edge_Cool_Fan_R_VMNDEA = '$vmndea[$j]',
				Film_Edge_Cool_Fan_R_VMNDER = '$vmnder[$j]',
				Film_Edge_Cool_Fan_R_TempM = '$tempm[$j]',
				Film_Edge_Cool_Fan_R_ArusR = '$arusr[$j]',
				Film_Edge_Cool_Fan_R_ArusS = '$aruss[$j]',
				Film_Edge_Cool_Fan_R_ArusT = '$arust[$j]',
				Film_Edge_Cool_Fan_R_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Edge_Guide_Fan_L_VMDE = '$vmde[$j]',
				Edge_Guide_Fan_L_VMNDEA = '$vmndea[$j]',
				Edge_Guide_Fan_L_VMNDER = '$vmnder[$j]',
				Edge_Guide_Fan_L_TempM = '$tempm[$j]',
				Edge_Guide_Fan_L_ArusR = '$arusr[$j]',
				Edge_Guide_Fan_L_ArusS = '$aruss[$j]',
				Edge_Guide_Fan_L_ArusT = '$arust[$j]',
				Edge_Guide_Fan_L_Ket = '$ket[$j]' WHERE Tanggal = '$date';");   $j++; $insert = mysql_query("UPDATE form_checklist_line_6_tdo SET
				Edge_Guide_Fan_R_VMDE = '$vmde[$j]',
				Edge_Guide_Fan_R_VMNDEA = '$vmndea[$j]',
				Edge_Guide_Fan_R_VMNDER = '$vmnder[$j]',
				Edge_Guide_Fan_R_TempM = '$tempm[$j]',
				Edge_Guide_Fan_R_ArusR = '$arusr[$j]',
				Edge_Guide_Fan_R_ArusS = '$aruss[$j]',
				Edge_Guide_Fan_R_ArusT = '$arust[$j]',
				Edge_Guide_Fan_R_Ket = '$ket[$j]' WHERE Tanggal = '$date';"); 
	if(!$insert){
		echo "<h1><script>alert('Form Checklist Line 6 TDO Tanggal ($date) Gagal Disimpan');</script></h1>";

echo "<h2><script>alert('Tidak Dapat Input Data Pada Tanggal Yang Sama');
		location.href='MainPageTab.php';</script></h2>";
	}
	else {
		include "WebTabelbacktotdoasline6.php";
	}						
}	
else{
	echo "Proses Salah";
}
?>

		
  