<?php
	include 'koneksi.php';
	
	$cek = mysql_select_db('checklist');
	if($cek)
	{
		//echo "<br>Database Benar</br>";
			   
		$tabel = 'CREATE TABLE form_checklist_line_5_tdo( '.
				'Tanggal DATE NOT NULL, '.
				'Nama VARCHAR(30) NOT NULL, '.
				'Fan_Preheat11_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Preheat11_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Preheat11_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Preheat11_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Preheat11_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Preheat11_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Preheat11_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Preheat11_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Preheat12_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Preheat12_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Preheat12_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Preheat12_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Preheat12_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Preheat12_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Preheat12_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Preheat12_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Preheat21_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Preheat21_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Preheat21_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Preheat21_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Preheat21_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Preheat21_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Preheat21_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Preheat21_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Preheat22_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Preheat22_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Preheat22_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Preheat22_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Preheat22_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Preheat22_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Preheat22_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Preheat22_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Preheat23_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Preheat23_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Preheat23_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Preheat23_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Preheat23_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Preheat23_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Preheat23_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Preheat23_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Preheat31_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Preheat31_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Preheat31_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Preheat31_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Preheat31_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Preheat31_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Preheat31_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Preheat31_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Preheat32_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Preheat32_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Preheat32_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Preheat32_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Preheat32_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Preheat32_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Preheat32_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Preheat32_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Preheat33_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Preheat33_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Preheat33_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Preheat33_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Preheat33_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Preheat33_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Preheat33_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Preheat33_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Drawing11_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Drawing11_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Drawing11_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Drawing11_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Drawing11_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Drawing11_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Drawing11_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Drawing11_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Drawing12_OS_Pump_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Drawing12_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Drawing12_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Drawing12_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Drawing12_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Drawing12_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Drawing12_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Drawing12_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Drawing21_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Drawing21_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Drawing21_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Drawing21_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Drawing21_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Drawing21_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Drawing21_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Drawing21_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Drawing22_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Drawing22_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Drawing22_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Drawing22_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Drawing22_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Drawing22_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Drawing22_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Drawing22_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Drawing31_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Drawing31_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Drawing31_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Drawing31_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Drawing31_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Drawing31_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Drawing31_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Drawing31_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Drawing32_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Drawing32_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Drawing32_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Drawing32_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Drawing32_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Drawing32_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Drawing32_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Drawing32_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Drawing41_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Drawing41_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Drawing41_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Drawing41_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Drawing41_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Drawing41_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Drawing41_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Drawing41_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Drawing42_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Drawing42_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Drawing42_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Drawing42_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Drawing42_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Drawing42_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Drawing42_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Drawing42_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Annealing11_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Annealing11_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Annealing11_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Annealing11_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Annealing11_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Annealing11_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Annealing11_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Annealing11_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Annealing12_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Annealing12_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Annealing12_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Annealing12_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Annealing12_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Annealing12_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Annealing12_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Annealing12_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Annealing21_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Annealing21_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Annealing21_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Annealing21_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Annealing21_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Annealing21_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Annealing21_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Annealing21_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Annealing22_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Annealing22_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Annealing22_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Annealing22_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Annealing22_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Annealing22_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Annealing22_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Annealing22_OS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Annealing31_DS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Annealing31_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Annealing31_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Annealing31_DS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Annealing31_DS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Annealing31_DS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Annealing31_DS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Annealing31_DS_Ket VARCHAR(50) NOT NULL, '.
				'Fan_Annealing32_OS_VMDE FLOAT(30) NOT NULL, '.
				'Fan_Annealing32_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Fan_Annealing32_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Fan_Annealing32_OS_TempM FLOAT(30) NOT NULL, '.
				'Fan_Annealing32_OS_ArusR FLOAT(30) NOT NULL, '.
				'Fan_Annealing32_OS_ArusS FLOAT(30) NOT NULL, '.
				'Fan_Annealing32_OS_ArusT FLOAT(30) NOT NULL, '.
				'Fan_Annealing32_OS_Ket VARCHAR(50) NOT NULL, '.
				'TDO_Airshow1_DS_VMDE FLOAT(30) NOT NULL, '.
				'TDO_Airshow1_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'TDO_Airshow1_DS_VMNDER FLOAT(30) NOT NULL, '.
				'TDO_Airshow1_DS_TempM FLOAT(30) NOT NULL, '.
				'TDO_Airshow1_DS_ArusR FLOAT(30) NOT NULL, '.
				'TDO_Airshow1_DS_ArusS FLOAT(30) NOT NULL, '.
				'TDO_Airshow1_DS_ArusT FLOAT(30) NOT NULL, '.
				'TDO_Airshow1_DS_Ket VARCHAR(50) NOT NULL, '.
				'TDO_Airshow2_OS_VMDE FLOAT(30) NOT NULL, '.
				'TDO_Airshow2_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'TDO_Airshow2_OS_VMNDER FLOAT(30) NOT NULL, '.
				'TDO_Airshow2_OS_TempM FLOAT(30) NOT NULL, '.
				'TDO_Airshow2_OS_ArusR FLOAT(30) NOT NULL, '.
				'TDO_Airshow2_OS_ArusS FLOAT(30) NOT NULL, '.
				'TDO_Airshow2_OS_ArusT FLOAT(30) NOT NULL, '.
				'TDO_Airshow2_OS_Ket VARCHAR(50) NOT NULL, '.
				'DC_Drive_TDO_VMDE FLOAT(30) NOT NULL, '.
				'DC_Drive_TDO_VMNDEA FLOAT(30) NOT NULL, '.
				'DC_Drive_TDO_VMNDER FLOAT(30) NOT NULL, '.
				'DC_Drive_TDO_TempM FLOAT(30) NOT NULL, '.
				'DC_Drive_TDO_ArusR FLOAT(30) NOT NULL, '.
				'DC_Drive_TDO_ArusS FLOAT(30) NOT NULL, '.
				'DC_Drive_TDO_ArusT FLOAT(30) NOT NULL, '.
				'DC_Drive_TDO_Ket VARCHAR(50) NOT NULL, '.
				'AC_Drive_Cool_TDO_VMDE FLOAT(30) NOT NULL, '.
				'AC_Drive_Cool_TDO_VMNDEA FLOAT(30) NOT NULL, '.
				'AC_Drive_Cool_TDO_VMNDER FLOAT(30) NOT NULL, '.
				'AC_Drive_Cool_TDO_TempM FLOAT(30) NOT NULL, '.
				'AC_Drive_Cool_TDO_ArusR FLOAT(30) NOT NULL, '.
				'AC_Drive_Cool_TDO_ArusS FLOAT(30) NOT NULL, '.
				'AC_Drive_Cool_TDO_ArusT FLOAT(30) NOT NULL, '.
				'AC_Drive_Cool_TDO_Ket VARCHAR(50) NOT NULL, '.
				'Edge_Guide_DS_VMDE FLOAT(30) NOT NULL, '.
				'Edge_Guide_DS_VMNDEA FLOAT(30) NOT NULL, '.
				'Edge_Guide_DS_VMNDER FLOAT(30) NOT NULL, '.
				'Edge_Guide_DS_TempM FLOAT(30) NOT NULL, '.
				'Edge_Guide_DS_ArusR FLOAT(30) NOT NULL, '.
				'Edge_Guide_DS_ArusS FLOAT(30) NOT NULL, '.
				'Edge_Guide_DS_ArusT FLOAT(30) NOT NULL, '.
				'Edge_Guide_DS_Ket VARCHAR(50) NOT NULL, '.
				'Edge_Guide_OS_VMDE FLOAT(30) NOT NULL, '.
				'Edge_Guide_OS_VMNDEA FLOAT(30) NOT NULL, '.
				'Edge_Guide_OS_VMNDER FLOAT(30) NOT NULL, '.
				'Edge_Guide_OS_TempM FLOAT(30) NOT NULL, '.
				'Edge_Guide_OS_ArusR FLOAT(30) NOT NULL, '.
				'Edge_Guide_OS_ArusS FLOAT(30) NOT NULL, '.
				'Edge_Guide_OS_ArusT FLOAT(30) NOT NULL, '.
				'Edge_Guide_OS_Ket VARCHAR(50) NOT NULL, '.
				'Bolt_Lubric_Pump_VMDE FLOAT(30) NOT NULL, '.
				'Bolt_Lubric_Pump_VMNDEA FLOAT(30) NOT NULL, '.
				'Bolt_Lubric_Pump_VMNDER FLOAT(30) NOT NULL, '.
				'Bolt_Lubric_Pump_TempM FLOAT(30) NOT NULL, '.
				'Bolt_Lubric_Pump_ArusR FLOAT(30) NOT NULL, '.
				'Bolt_Lubric_Pump_ArusS FLOAT(30) NOT NULL, '.
				'Bolt_Lubric_Pump_ArusT FLOAT(30) NOT NULL, '.
				'Bolt_Lubric_Pump_Ket VARCHAR(50) NOT NULL, '.
				'Chain_Lubric_Pump_VMDE FLOAT(30) NOT NULL, '.
				'Chain_Lubric_Pump_VMNDEA FLOAT(30) NOT NULL, '.
				'Chain_Lubric_Pump_VMNDER FLOAT(30) NOT NULL, '.
				'Chain_Lubric_Pump_TempM FLOAT(30) NOT NULL, '.
				'Chain_Lubric_Pump_ArusR FLOAT(30) NOT NULL, '.
				'Chain_Lubric_Pump_ArusS FLOAT(30) NOT NULL, '.
				'Chain_Lubric_Pump_ArusT FLOAT(30) NOT NULL, '.
				'Chain_Lubric_Pump_Ket VARCHAR(50) NOT NULL, '.
				'primary key ( Tanggal ))';		
		
		$databasetabel = mysql_query( $tabel );
		if($databasetabel)
		{
			echo "<h1>Tabel Berhasil Dibuat</h1></br>";
		}
		else
		{
			echo "<br><h1>Tabel Gagal Dibuat</h1></br>";
		}
	}
	else
	{
		echo "<br>Database Salah</br>";
	}
?>