<?php
	include 'koneksi.php';
	
	$cek = mysql_select_db('checklist');
	if($cek)
	{
		//echo "<br>Database Benar</br>";
			   
		$tabel = 'CREATE TABLE form_checklist_line_6_TDO( '.
				'Tanggal DATE NOT NULL, '.
				'Nama VARCHAR(30) NOT NULL, '.
				'Set_Vibrasi FLOAT(30) NOT NULL, '.
				'Set_Temperature FLOAT(30) NOT NULL, '.
				'Set_Arus FLOAT(30) NOT NULL, '.
				'Line_Drive_OL_VMDE FLOAT(30) NOT NULL, '.
				'Line_Drive_OL_VMNDEA FLOAT(30) NOT NULL, '.
				'Line_Drive_OL_VMNDER FLOAT(30) NOT NULL, '.
				'Line_Drive_OL_TempM FLOAT(30) NOT NULL, '.
				'Line_Drive_OL_ArusR FLOAT(30) NOT NULL, '.
				'Line_Drive_OL_ArusS FLOAT(30) NOT NULL, '.
				'Line_Drive_OL_ArusT FLOAT(30) NOT NULL, '.
				'Line_Drive_OL_Ket VARCHAR(50) NOT NULL, '.
				'Cooling_Drive_OL_VMDE FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OL_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OL_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OL_TempM FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OL_ArusR FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OL_ArusS FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OL_ArusT FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OL_Ket VARCHAR(50) NOT NULL, '.
				'Line_Drive_OR_VMDE FLOAT(30) NOT NULL, '.
				'Line_Drive_OR_VMNDEA FLOAT(30) NOT NULL, '.
				'Line_Drive_OR_VMNDER FLOAT(30) NOT NULL, '.
				'Line_Drive_OR_TempM FLOAT(30) NOT NULL, '.
				'Line_Drive_OR_ArusR FLOAT(30) NOT NULL, '.
				'Line_Drive_OR_ArusS FLOAT(30) NOT NULL, '.
				'Line_Drive_OR_ArusT FLOAT(30) NOT NULL, '.
				'Line_Drive_OR_Ket VARCHAR(50) NOT NULL, '.
				'Cooling_Drive_OR_VMDE FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OR_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OR_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OR_TempM FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OR_ArusR FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OR_ArusS FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OR_ArusT FLOAT(30) NOT NULL, '.
				'Cooling_Drive_OR_Ket VARCHAR(50) NOT NULL, '.
				'Preheat1_Fan1_VMDE FLOAT(30) NOT NULL, '.
				'Preheat1_Fan1_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat1_Fan1_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat1_Fan1_TempM FLOAT(30) NOT NULL, '.
				'Preheat1_Fan1_ArusR FLOAT(30) NOT NULL, '.
				'Preheat1_Fan1_ArusS FLOAT(30) NOT NULL, '.
				'Preheat1_Fan1_ArusT FLOAT(30) NOT NULL, '.
				'Preheat1_Fan1_Ket VARCHAR(50) NOT NULL, '.
				'Preheat1_Fan2_VMDE FLOAT(30) NOT NULL, '.
				'Preheat1_Fan2_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat1_Fan2_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat1_Fan2_TempM FLOAT(30) NOT NULL, '.
				'Preheat1_Fan2_ArusR FLOAT(30) NOT NULL, '.
				'Preheat1_Fan2_ArusS FLOAT(30) NOT NULL, '.
				'Preheat1_Fan2_ArusT FLOAT(30) NOT NULL, '.
				'Preheat1_Fan2_Ket VARCHAR(50) NOT NULL, '.
				'Preheat1_Fan3_VMDE FLOAT(30) NOT NULL, '.
				'Preheat1_Fan3_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat1_Fan3_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat1_Fan3_TempM FLOAT(30) NOT NULL, '.
				'Preheat1_Fan3_ArusR FLOAT(30) NOT NULL, '.
				'Preheat1_Fan3_ArusS FLOAT(30) NOT NULL, '.
				'Preheat1_Fan3_ArusT FLOAT(30) NOT NULL, '.
				'Preheat1_Fan3_Ket VARCHAR(50) NOT NULL, '.
				'Preheat2_Fan1_VMDE FLOAT(30) NOT NULL, '.
				'Preheat2_Fan1_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat2_Fan1_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat2_Fan1_TempM FLOAT(30) NOT NULL, '.
				'Preheat2_Fan1_ArusR FLOAT(30) NOT NULL, '.
				'Preheat2_Fan1_ArusS FLOAT(30) NOT NULL, '.
				'Preheat2_Fan1_ArusT FLOAT(30) NOT NULL, '.
				'Preheat2_Fan1_Ket VARCHAR(50) NOT NULL, '.
				'Preheat2_Fan2_VMDE FLOAT(30) NOT NULL, '.
				'Preheat2_Fan2_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat2_Fan2_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat2_Fan2_TempM FLOAT(30) NOT NULL, '.
				'Preheat2_Fan2_ArusR FLOAT(30) NOT NULL, '.
				'Preheat2_Fan2_ArusS FLOAT(30) NOT NULL, '.
				'Preheat2_Fan2_ArusT FLOAT(30) NOT NULL, '.
				'Preheat2_Fan2_Ket VARCHAR(50) NOT NULL, '.
				'Preheat2_Fan3_VMDE FLOAT(30) NOT NULL, '.
				'Preheat2_Fan3_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat2_Fan3_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat2_Fan3_TempM FLOAT(30) NOT NULL, '.
				'Preheat2_Fan3_ArusR FLOAT(30) NOT NULL, '.
				'Preheat2_Fan3_ArusS FLOAT(30) NOT NULL, '.
				'Preheat2_Fan3_ArusT FLOAT(30) NOT NULL, '.
				'Preheat2_Fan3_Ket VARCHAR(50) NOT NULL, '.
				'Preheat3_Fan1_VMDE FLOAT(30) NOT NULL, '.
				'Preheat3_Fan1_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat3_Fan1_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat3_Fan1_TempM FLOAT(30) NOT NULL, '.
				'Preheat3_Fan1_ArusR FLOAT(30) NOT NULL, '.
				'Preheat3_Fan1_ArusS FLOAT(30) NOT NULL, '.
				'Preheat3_Fan1_ArusT FLOAT(30) NOT NULL, '.
				'Preheat3_Fan1_Ket VARCHAR(50) NOT NULL, '.
				'Preheat3_Fan2_VMDE FLOAT(30) NOT NULL, '.
				'Preheat3_Fan2_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat3_Fan2_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat3_Fan2_TempM FLOAT(30) NOT NULL, '.
				'Preheat3_Fan2_ArusR FLOAT(30) NOT NULL, '.
				'Preheat3_Fan2_ArusS FLOAT(30) NOT NULL, '.
				'Preheat3_Fan2_ArusT FLOAT(30) NOT NULL, '.
				'Preheat3_Fan2_Ket VARCHAR(50) NOT NULL, '.
				'Preheat3_Fan3_VMDE FLOAT(30) NOT NULL, '.
				'Preheat3_Fan3_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat3_Fan3_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat3_Fan3_TempM FLOAT(30) NOT NULL, '.
				'Preheat3_Fan3_ArusR FLOAT(30) NOT NULL, '.
				'Preheat3_Fan3_ArusS FLOAT(30) NOT NULL, '.
				'Preheat3_Fan3_ArusT FLOAT(30) NOT NULL, '.
				'Preheat3_Fan3_Ket VARCHAR(50) NOT NULL, '.
				'Preheat4_Fan1_VMDE FLOAT(30) NOT NULL, '.
				'Preheat4_Fan1_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat4_Fan1_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat4_Fan1_TempM FLOAT(30) NOT NULL, '.
				'Preheat4_Fan1_ArusR FLOAT(30) NOT NULL, '.
				'Preheat4_Fan1_ArusS FLOAT(30) NOT NULL, '.
				'Preheat4_Fan1_ArusT FLOAT(30) NOT NULL, '.
				'Preheat4_Fan1_Ket VARCHAR(50) NOT NULL, '.
				'Preheat4_Fan2_VMDE FLOAT(30) NOT NULL, '.
				'Preheat4_Fan2_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat4_Fan2_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat4_Fan2_TempM FLOAT(30) NOT NULL, '.
				'Preheat4_Fan2_ArusR FLOAT(30) NOT NULL, '.
				'Preheat4_Fan2_ArusS FLOAT(30) NOT NULL, '.
				'Preheat4_Fan2_ArusT FLOAT(30) NOT NULL, '.
				'Preheat4_Fan2_Ket VARCHAR(50) NOT NULL, '.
				'Preheat4_Fan3_VMDE FLOAT(30) NOT NULL, '.
				'Preheat4_Fan3_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat4_Fan3_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat4_Fan3_TempM FLOAT(30) NOT NULL, '.
				'Preheat4_Fan3_ArusR FLOAT(30) NOT NULL, '.
				'Preheat4_Fan3_ArusS FLOAT(30) NOT NULL, '.
				'Preheat4_Fan3_ArusT FLOAT(30) NOT NULL, '.
				'Preheat4_Fan3_Ket VARCHAR(50) NOT NULL, '.
				'Preheat5_Fan1_VMDE FLOAT(30) NOT NULL, '.
				'Preheat5_Fan1_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat5_Fan1_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat5_Fan1_TempM FLOAT(30) NOT NULL, '.
				'Preheat5_Fan1_ArusR FLOAT(30) NOT NULL, '.
				'Preheat5_Fan1_ArusS FLOAT(30) NOT NULL, '.
				'Preheat5_Fan1_ArusT FLOAT(30) NOT NULL, '.
				'Preheat5_Fan1_Ket VARCHAR(50) NOT NULL, '.
				'Preheat5_Fan2_VMDE FLOAT(30) NOT NULL, '.
				'Preheat5_Fan2_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat5_Fan2_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat5_Fan2_TempM FLOAT(30) NOT NULL, '.
				'Preheat5_Fan2_ArusR FLOAT(30) NOT NULL, '.
				'Preheat5_Fan2_ArusS FLOAT(30) NOT NULL, '.
				'Preheat5_Fan2_ArusT FLOAT(30) NOT NULL, '.
				'Preheat5_Fan2_Ket VARCHAR(50) NOT NULL, '.
				'Preheat5_Fan3_VMDE FLOAT(30) NOT NULL, '.
				'Preheat5_Fan3_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat5_Fan3_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat5_Fan3_TempM FLOAT(30) NOT NULL, '.
				'Preheat5_Fan3_ArusR FLOAT(30) NOT NULL, '.
				'Preheat5_Fan3_ArusS FLOAT(30) NOT NULL, '.
				'Preheat5_Fan3_ArusT FLOAT(30) NOT NULL, '.
				'Preheat5_Fan3_Ket VARCHAR(50) NOT NULL, '.
				'Preheat6_Fan1_VMDE FLOAT(30) NOT NULL, '.
				'Preheat6_Fan1_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat6_Fan1_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat6_Fan1_TempM FLOAT(30) NOT NULL, '.
				'Preheat6_Fan1_ArusR FLOAT(30) NOT NULL, '.
				'Preheat6_Fan1_ArusS FLOAT(30) NOT NULL, '.
				'Preheat6_Fan1_ArusT FLOAT(30) NOT NULL, '.
				'Preheat6_Fan1_Ket VARCHAR(50) NOT NULL, '.
				'Preheat6_Fan2_VMDE FLOAT(30) NOT NULL, '.
				'Preheat6_Fan2_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat6_Fan2_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat6_Fan2_TempM FLOAT(30) NOT NULL, '.
				'Preheat6_Fan2_ArusR FLOAT(30) NOT NULL, '.
				'Preheat6_Fan2_ArusS FLOAT(30) NOT NULL, '.
				'Preheat6_Fan2_ArusT FLOAT(30) NOT NULL, '.
				'Preheat6_Fan2_Ket VARCHAR(50) NOT NULL, '.
				'Preheat6_Fan3_VMDE FLOAT(30) NOT NULL, '.
				'Preheat6_Fan3_VMNDEA FLOAT(30) NOT NULL, '.
				'Preheat6_Fan3_VMNDER FLOAT(30) NOT NULL, '.
				'Preheat6_Fan3_TempM FLOAT(30) NOT NULL, '.
				'Preheat6_Fan3_ArusR FLOAT(30) NOT NULL, '.
				'Preheat6_Fan3_ArusS FLOAT(30) NOT NULL, '.
				'Preheat6_Fan3_ArusT FLOAT(30) NOT NULL, '.
				'Preheat6_Fan3_Ket VARCHAR(50) NOT NULL, '.
				'Drawing1_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing1_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing1_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing1_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing1_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing1_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing2_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing2_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing2_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing2_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing2_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing2_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing3_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing3_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing3_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing3_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing3_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing3_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing4_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing4_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing4_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing4_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing4_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing4_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing5_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing5_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Drawing5_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing5_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Drawing5_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Drawing5_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing1_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing1_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing1_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing1_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing1_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing1_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing2_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing2_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing2_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing2_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing2_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing2_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing3_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing3_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing3_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing3_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing3_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing3_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing4_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing4_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing4_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing4_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing4_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing4_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing5_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing5_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing5_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing5_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing5_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing5_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing6_Fan1_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing6_Fan2_Top_VMDE FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Top_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Top_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Top_TempM FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Top_ArusR FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Top_ArusS FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Top_ArusT FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Top_Ket VARCHAR(50) NOT NULL, '.
				'Annealing6_Fan1_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing6_Fan1_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Annealing6_Fan2_Bot_VMDE FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Bot_VMNDEA FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Bot_VMNDER FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Bot_TempM FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Bot_ArusR FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Bot_ArusS FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Bot_ArusT FLOAT(30) NOT NULL, '.
				'Annealing6_Fan2_Bot_Ket VARCHAR(50) NOT NULL, '.
				'Film_Edge_Cool_Fan_L_VMDE FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_L_VMNDEA FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_L_VMNDER FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_L_TempM FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_L_ArusR FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_L_ArusS FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_L_ArusT FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_L_Ket VARCHAR(50) NOT NULL, '.
				'Film_Edge_Cool_Fan_R_VMDE FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_R_VMNDEA FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_R_VMNDER FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_R_TempM FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_R_ArusR FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_R_ArusS FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_R_ArusT FLOAT(30) NOT NULL, '.
				'Film_Edge_Cool_Fan_R_Ket VARCHAR(50) NOT NULL, '.
				'Edge_Guide_Fan_L_VMDE FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_L_VMNDEA FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_L_VMNDER FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_L_TempM FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_L_ArusR FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_L_ArusS FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_L_ArusT FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_L_Ket VARCHAR(50) NOT NULL, '.
				'Edge_Guide_Fan_R_VMDE FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_R_VMNDEA FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_R_VMNDER FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_R_TempM FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_R_ArusR FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_R_ArusS FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_R_ArusT FLOAT(30) NOT NULL, '.
				'Edge_Guide_Fan_R_Ket VARCHAR(50) NOT NULL, '.
				'primary key ( Tanggal ))';		
		
		$databasetabel = mysql_query( $tabel );
		if($databasetabel)
		{
			echo "<h1>Tabel Berhasil Dibuat</h1></br>";
		}
		else
		{
			echo "<br><h1>Tabel Gagal Dibuat</h1></br>";
		}
	}
	else
	{
		echo "<br>Database Salah</br>";
	}
?>