<?php
	include 'koneksi.php';
	
	$cek = mysql_select_db('checklist');
	if($cek)
	{
		//echo "<br>Database Benar</br>";
			   
		$tabel = 'CREATE TABLE form_checklist_line_6_TDOAS( '.
				'Tanggal DATE NOT NULL, '.
				'Nama VARCHAR(30) NOT NULL, '.
				'Cooling1_Fan1_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling1_Fan1_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling1_Fan2_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling1_Fan2_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling1_Fan1_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling1_Fan1_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling1_Fan1_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling1_Fan2_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling1_Fan2_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling1_Fan2_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling2_Fan1_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling2_Fan1_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling2_Fan2_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling2_Fan2_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling2_Fan1_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling2_Fan1_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling2_Fan1_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling2_Fan2_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling2_Fan2_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling2_Fan2_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling3_Fan1_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling3_Fan1_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling3_Fan2_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling3_Fan2_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling3_Fan1_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling3_Fan1_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling3_Fan1_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling3_Fan2_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling3_Fan2_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling3_Fan2_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling4_Fan1_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling4_Fan1_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling4_Fan2_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling4_Fan2_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling4_Fan1_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling4_Fan1_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling4_Fan1_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling4_Fan2_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling4_Fan2_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling4_Fan2_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling5_Fan1_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling5_Fan1_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling5_Fan2_Top1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top1_TempM FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling5_Fan2_Top2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top2_TempM FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Top2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling5_Fan1_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling5_Fan1_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling5_Fan1_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'Cooling5_Fan2_Bot1_VMDE FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot1_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot1_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot1_TempM FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot1_ArusR FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot1_ArusS FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot1_ArusT FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot1_Ket VARCHAR(50) NOT NULL, '.
				'Cooling5_Fan2_Bot2_VMDE FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot2_VMNDEA FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot2_VMNDER FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot2_TempM FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot2_ArusR FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot2_ArusS FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot2_ArusT FLOAT(30) NOT NULL, '.
				'Cooling5_Fan2_Bot2_Ket VARCHAR(50) NOT NULL, '.
				'primary key ( Tanggal ))';		
		
		$databasetabel = mysql_query( $tabel );
		if($databasetabel)
		{
			echo "<h1>Tabel Berhasil Dibuat</h1></br>";
		}
		else
		{
			echo "<br><h1>Tabel Gagal Dibuat</h1></br>";
		}
	}
	else
	{
		echo "<br>Database Salah</br>";
	}
?>