<?php
	include 'koneksi.php';
	
	$cek = mysql_select_db('checklist');
	if($cek)
	{
		//echo "<br>Database Benar</br>";
			   
		$tabel = 'CREATE TABLE form_checklist_line_5_ext( '.
				'Tanggal DATE NOT NULL, '.
				'Nama VARCHAR(30) NOT NULL, '.
				'DC_MExt_VMDE FLOAT(30) NOT NULL, '.
				'DC_MExt_VMNDEA FLOAT(30) NOT NULL, '.
				'DC_MExt_VMNDER FLOAT(30) NOT NULL, '.
				'DC_MExt_TempM FLOAT(30) NOT NULL, '.
				'DC_MExt_ArusR FLOAT(30) NOT NULL, '.
				'DC_MExt_ArusS FLOAT(30) NOT NULL, '.
				'DC_MExt_ArusT FLOAT(30) NOT NULL, '.
				'DC_MExt_Ket VARCHAR(50) NOT NULL, '.
				'MExt_Fan_Cool_Blow_VMDE FLOAT(30) NOT NULL, '.
				'MExt_Fan_Cool_Blow_VMNDEA FLOAT(30) NOT NULL, '.
				'MExt_Fan_Cool_Blow_VMNDER FLOAT(30) NOT NULL, '.
				'MExt_Fan_Cool_Blow_TempM FLOAT(30) NOT NULL, '.
				'MExt_Fan_Cool_Blow_ArusR FLOAT(30) NOT NULL, '.
				'MExt_Fan_Cool_Blow_ArusS FLOAT(30) NOT NULL, '.
				'MExt_Fan_Cool_Blow_ArusT FLOAT(30) NOT NULL, '.
				'MExt_Fan_Cool_Blow_Ket VARCHAR(50) NOT NULL, '.
				'DC_Meter_Ext_VMDE FLOAT(30) NOT NULL, '.
				'DC_Meter_Ext_VMNDEA FLOAT(30) NOT NULL, '.
				'DC_Meter_Ext_VMNDER FLOAT(30) NOT NULL, '.
				'DC_Meter_Ext_TempM FLOAT(30) NOT NULL, '.
				'DC_Meter_Ext_ArusR FLOAT(30) NOT NULL, '.
				'DC_Meter_Ext_ArusS FLOAT(30) NOT NULL, '.
				'DC_Meter_Ext_ArusT FLOAT(30) NOT NULL, '.
				'DC_Meter_Ext_Ket VARCHAR(50) NOT NULL, '.
				'Meter_Fan_Cool_Blow_VMDE FLOAT(30) NOT NULL, '.
				'Meter_Fan_Cool_Blow_VMNDEA FLOAT(30) NOT NULL, '.
				'Meter_Fan_Cool_Blow_VMNDER FLOAT(30) NOT NULL, '.
				'Meter_Fan_Cool_Blow_TempM FLOAT(30) NOT NULL, '.
				'Meter_Fan_Cool_Blow_ArusR FLOAT(30) NOT NULL, '.
				'Meter_Fan_Cool_Blow_ArusS FLOAT(30) NOT NULL, '.
				'Meter_Fan_Cool_Blow_ArusT FLOAT(30) NOT NULL, '.
				'Meter_Fan_Cool_Blow_Ket VARCHAR(50) NOT NULL, '.
				'DC_CoExt1_VMDE FLOAT(30) NOT NULL, '.
				'DC_CoExt1_VMNDEA FLOAT(30) NOT NULL, '.
				'DC_CoExt1_VMNDER FLOAT(30) NOT NULL, '.
				'DC_CoExt1_TempM FLOAT(30) NOT NULL, '.
				'DC_CoExt1_ArusR FLOAT(30) NOT NULL, '.
				'DC_CoExt1_ArusS FLOAT(30) NOT NULL, '.
				'DC_CoExt1_ArusT FLOAT(30) NOT NULL, '.
				'DC_CoExt1_Ket VARCHAR(50) NOT NULL, '.
				'CoExt1_Cool_Blow_Fan_VMDE FLOAT(30) NOT NULL, '.
				'CoExt1_Cool_Blow_Fan_VMNDEA FLOAT(30) NOT NULL, '.
				'CoExt1_Cool_Blow_Fan_VMNDER FLOAT(30) NOT NULL, '.
				'CoExt1_Cool_Blow_Fan_TempM FLOAT(30) NOT NULL, '.
				'CoExt1_Cool_Blow_Fan_ArusR FLOAT(30) NOT NULL, '.
				'CoExt1_Cool_Blow_Fan_ArusS FLOAT(30) NOT NULL, '.
				'CoExt1_Cool_Blow_Fan_ArusT FLOAT(30) NOT NULL, '.
				'CoExt1_Cool_Blow_Fan_Ket VARCHAR(50) NOT NULL, '.
				'DC_CoExt2_VMDE FLOAT(30) NOT NULL, '.
				'DC_CoExt2_VMNDEA FLOAT(30) NOT NULL, '.
				'DC_CoExt2_VMNDER FLOAT(30) NOT NULL, '.
				'DC_CoExt2_TempM FLOAT(30) NOT NULL, '.
				'DC_CoExt2_ArusR FLOAT(30) NOT NULL, '.
				'DC_CoExt2_ArusS FLOAT(30) NOT NULL, '.
				'DC_CoExt2_ArusT FLOAT(30) NOT NULL, '.
				'DC_CoExt2_Ket VARCHAR(50) NOT NULL, '.
				'CoExt2_Cool_Blow_Fan_VMDE FLOAT(30) NOT NULL, '.
				'CoExt2_Cool_Blow_Fan_VMNDEA FLOAT(30) NOT NULL, '.
				'CoExt2_Cool_Blow_Fan_VMNDER FLOAT(30) NOT NULL, '.
				'CoExt2_Cool_Blow_Fan_TempM FLOAT(30) NOT NULL, '.
				'CoExt2_Cool_Blow_Fan_ArusR FLOAT(30) NOT NULL, '.
				'CoExt2_Cool_Blow_Fan_ArusS FLOAT(30) NOT NULL, '.
				'CoExt2_Cool_Blow_Fan_ArusT FLOAT(30) NOT NULL, '.
				'CoExt2_Cool_Blow_Fan_Ket VARCHAR(50) NOT NULL, '.
				'MExt_Gear_Oil_Pump_VMDE FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump_VMNDEA FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump_VMNDER FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump_TempM FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump_ArusR FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump_ArusS FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump_ArusT FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump_Ket VARCHAR(50) NOT NULL, '.
				'MExt_Gear_Oil_Pump1_VMDE FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump1_VMNDEA FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump1_VMNDER FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump1_TempM FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump1_ArusR FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump1_ArusS FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump1_ArusT FLOAT(30) NOT NULL, '.
				'MExt_Gear_Oil_Pump1_Ket VARCHAR(50) NOT NULL, '.
				'MExt_Filter_Preheat_Pump2_VMDE FLOAT(30) NOT NULL, '.
				'MExt_Filter_Preheat_Pump2_VMNDEA FLOAT(30) NOT NULL, '.
				'MExt_Filter_Preheat_Pump2_VMNDER FLOAT(30) NOT NULL, '.
				'MExt_Filter_Preheat_Pump2_TempM FLOAT(30) NOT NULL, '.
				'MExt_Filter_Preheat_Pump2_ArusR FLOAT(30) NOT NULL, '.
				'MExt_Filter_Preheat_Pump2_ArusS FLOAT(30) NOT NULL, '.
				'MExt_Filter_Preheat_Pump2_ArusT FLOAT(30) NOT NULL, '.
				'MExt_Filter_Preheat_Pump2_Ket VARCHAR(50) NOT NULL, '.
				'Meter_Ext_Gear_Oil_Pump_VMDE FLOAT(30) NOT NULL, '.
				'Meter_Ext_Gear_Oil_Pump_VMNDEA FLOAT(30) NOT NULL, '.
				'Meter_Ext_Gear_Oil_Pump_VMNDER FLOAT(30) NOT NULL, '.
				'Meter_Ext_Gear_Oil_Pump_TempM FLOAT(30) NOT NULL, '.
				'Meter_Ext_Gear_Oil_Pump_ArusR FLOAT(30) NOT NULL, '.
				'Meter_Ext_Gear_Oil_Pump_ArusS FLOAT(30) NOT NULL, '.
				'Meter_Ext_Gear_Oil_Pump_ArusT FLOAT(30) NOT NULL, '.
				'Meter_Ext_Gear_Oil_Pump_Ket VARCHAR(50) NOT NULL, '.
				'CoExt1_Autoload_VMDE FLOAT(30) NOT NULL, '.
				'CoExt1_Autoload_VMNDEA FLOAT(30) NOT NULL, '.
				'CoExt1_Autoload_VMNDER FLOAT(30) NOT NULL, '.
				'CoExt1_Autoload_TempM FLOAT(30) NOT NULL, '.
				'CoExt1_Autoload_ArusR FLOAT(30) NOT NULL, '.
				'CoExt1_Autoload_ArusS FLOAT(30) NOT NULL, '.
				'CoExt1_Autoload_ArusT FLOAT(30) NOT NULL, '.
				'CoExt1_Autoload_Ket VARCHAR(50) NOT NULL, '.
				'CoExt2_Autoload_VMDE FLOAT(30) NOT NULL, '.
				'CoExt2_Autoload_VMNDEA FLOAT(30) NOT NULL, '.
				'CoExt2_Autoload_VMNDER FLOAT(30) NOT NULL, '.
				'CoExt2_Autoload_TempM FLOAT(30) NOT NULL, '.
				'CoExt2_Autoload_ArusR FLOAT(30) NOT NULL, '.
				'CoExt2_Autoload_ArusS FLOAT(30) NOT NULL, '.
				'CoExt2_Autoload_ArusT FLOAT(30) NOT NULL, '.
				'CoExt2_Autoload_Ket VARCHAR(50) NOT NULL, '.
				'EA_Panel_Temp_VMDE FLOAT(30) NOT NULL, '.
				'EA_Panel_Temp_VMNDEA FLOAT(30) NOT NULL, '.
				'EA_Panel_Temp_VMNDER FLOAT(30) NOT NULL, '.
				'EA_Panel_Temp_TempM FLOAT(30) NOT NULL, '.
				'EA_Panel_Temp_ArusR FLOAT(30) NOT NULL, '.
				'EA_Panel_Temp_ArusS FLOAT(30) NOT NULL, '.
				'EA_Panel_Temp_ArusT FLOAT(30) NOT NULL, '.
				'EA_Panel_Temp_Ket VARCHAR(50) NOT NULL, '.
				'Cascade_Ext_Temp_VMDE FLOAT(30) NOT NULL, '.
				'Cascade_Ext_Temp_VMNDEA FLOAT(30) NOT NULL, '.
				'Cascade_Ext_Temp_VMNDER FLOAT(30) NOT NULL, '.
				'Cascade_Ext_Temp_TempM FLOAT(30) NOT NULL, '.
				'Cascade_Ext_Temp_ArusR FLOAT(30) NOT NULL, '.
				'Cascade_Ext_Temp_ArusS FLOAT(30) NOT NULL, '.
				'Cascade_Ext_Temp_ArusT FLOAT(30) NOT NULL, '.
				'Cascade_Ext_Temp_Ket VARCHAR(50) NOT NULL, '.
				'Control_Room_Temp_VMDE FLOAT(30) NOT NULL, '.
				'Control_Room_Temp_VMNDEA FLOAT(30) NOT NULL, '.
				'Control_Room_Temp_VMNDER FLOAT(30) NOT NULL, '.
				'Control_Room_Temp_TempM FLOAT(30) NOT NULL, '.
				'Control_Room_Temp_ArusR FLOAT(30) NOT NULL, '.
				'Control_Room_Temp_ArusS FLOAT(30) NOT NULL, '.
				'Control_Room_Temp_ArusT FLOAT(30) NOT NULL, '.
				'Control_Room_Temp_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt1_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt1_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt1_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt1_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt1_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt1_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt1_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt1_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt2_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt2_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt2_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt2_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt2_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt2_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt2_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt2_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt3_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt3_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt3_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt3_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt3_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt3_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt3_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt3_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt4_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt4_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt4_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt4_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt4_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt4_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt4_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt4_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt5_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt5_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt5_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt5_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt5_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt5_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt5_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt5_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt6_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt6_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt6_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt6_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt6_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt6_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt6_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt6_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt7_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt7_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt7_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt7_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt7_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt7_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt7_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt7_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt8_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt8_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt8_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt8_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt8_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt8_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt8_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt8_Ket VARCHAR(50) NOT NULL, '.
				'Heater_MExt9_VMDE FLOAT(30) NOT NULL, '.
				'Heater_MExt9_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_MExt9_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_MExt9_TempM FLOAT(30) NOT NULL, '.
				'Heater_MExt9_ArusR FLOAT(30) NOT NULL, '.
				'Heater_MExt9_ArusS FLOAT(30) NOT NULL, '.
				'Heater_MExt9_ArusT FLOAT(30) NOT NULL, '.
				'Heater_MExt9_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext1_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext1_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext1_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext1_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext1_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext1_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext1_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext1_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext2_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext2_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext2_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext2_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext2_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext2_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext2_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext2_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext3_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext3_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext3_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext3_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext3_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext3_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext3_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext3_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext4_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext4_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext4_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext4_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext4_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext4_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext4_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext4_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext5_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext5_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext5_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext5_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext5_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext5_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext5_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext5_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext6_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext6_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext6_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext6_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext6_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext6_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext6_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext6_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext7_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext7_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext7_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext7_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext7_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext7_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext7_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext7_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext8_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext8_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext8_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext8_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext8_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext8_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext8_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext8_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext9_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext9_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext9_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext9_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext9_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext9_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext9_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext9_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext10_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext10_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext10_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext10_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext10_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext10_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext10_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext10_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext11_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext11_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext11_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext11_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext11_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext11_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext11_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext11_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext12_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext12_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext12_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext12_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext12_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext12_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext12_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext12_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext13_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext13_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext13_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext13_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext13_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext13_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext13_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext13_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext14_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext14_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext14_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext14_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext14_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext14_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext14_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext14_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext15_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext15_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext15_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext15_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext15_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext15_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext15_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext15_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext16_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext16_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext16_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext16_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext16_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext16_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext16_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext16_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext17_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext17_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext17_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext17_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext17_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext17_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext17_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext17_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext18_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext18_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext18_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext18_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext18_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext18_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext18_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext18_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext19_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext19_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext19_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext19_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext19_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext19_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext19_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext19_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext20_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext20_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext20_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext20_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext20_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext20_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext20_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext20_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext21_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext21_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext21_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext21_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext21_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext21_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext21_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext21_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext22_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext22_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext22_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext22_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext22_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext22_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext22_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext22_Ket VARCHAR(50) NOT NULL, '.
				'Heater_Meter_Ext23_VMDE FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext23_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext23_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext23_TempM FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext23_ArusR FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext23_ArusS FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext23_ArusT FLOAT(30) NOT NULL, '.
				'Heater_Meter_Ext23_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_1_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_1_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_1_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_1_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_1_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_1_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_1_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_1_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_2_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_2_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_2_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_2_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_2_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_2_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_2_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_2_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_3_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_3_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_3_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_3_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_3_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_3_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_3_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_3_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_4_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_4_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_4_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_4_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_4_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_4_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_4_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_4_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_5_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_5_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_5_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_5_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_5_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_5_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_5_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_5_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_6_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_6_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_6_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_6_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_6_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_6_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_6_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_6_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_7_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_7_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_7_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_7_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_7_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_7_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_7_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_7_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_8_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_8_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_8_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_8_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_8_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_8_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_8_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_8_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_9_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_9_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_9_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_9_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_9_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_9_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_9_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_9_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_10_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_10_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_10_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_10_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_10_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_10_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_10_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_10_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt1_11_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_11_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_11_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_11_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_11_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_11_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_11_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt1_11_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_1_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_1_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_1_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_1_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_1_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_1_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_1_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_1_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_2_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_2_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_2_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_2_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_2_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_2_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_2_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_2_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_3_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_3_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_3_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_3_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_3_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_3_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_3_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_3_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_4_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_4_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_4_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_4_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_4_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_4_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_4_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_4_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_5_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_5_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_5_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_5_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_5_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_5_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_5_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_5_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_6_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_6_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_6_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_6_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_6_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_6_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_6_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_6_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_7_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_7_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_7_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_7_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_7_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_7_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_7_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_7_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_8_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_8_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_8_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_8_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_8_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_8_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_8_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_8_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_9_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_9_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_9_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_9_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_9_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_9_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_9_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_9_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_10_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_10_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_10_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_10_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_10_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_10_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_10_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_10_Ket VARCHAR(50) NOT NULL, '.
				'Heater_CoExt2_11_VMDE FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_11_VMNDEA FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_11_VMNDER FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_11_TempM FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_11_ArusR FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_11_ArusS FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_11_ArusT FLOAT(30) NOT NULL, '.
				'Heater_CoExt2_11_Ket VARCHAR(50) NOT NULL, '.
				'primary key ( Tanggal ))';		
		
		$databasetabel = mysql_query( $tabel );
		if($databasetabel)
		{
			echo "<h1>Tabel Berhasil Dibuat</h1></br>";
		}
		else
		{
			echo "<br><h1>Tabel Gagal Dibuat</h1></br>";
		}
	}
	else
	{
		echo "<br>Database Salah</br>";
	}
?>